services:
  postgres: 
    image: postgres:13
    container_name: data_warehouse_olympics
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Olympic_Data_Warehouse_main
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql_scripts/postgres-init-db:/docker-entrypoint-initdb.d
volumes:
  pgdata: